id: P005372
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5333
  title: བླ་མ་ཨོ་རྒྱན་ཆེན་པོ་རྗེས་སུ་དྲན་པའི་ཆོས་ཚན་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    79721dc60a0d4cf3a85949362bce3913:
      image_group_id: I3CN5335
      title: ''
      volume_number: 1
      total_pages: 324
      base_file: v001.txt
