id: I35A9A1CE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:12:29+00:00'
last_modified: '2022-06-08T02:37:09.711307+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5333
  title: བླ་མ་ཨོ་རྒྱན་ཆེན་པོ་རྗེས་སུ་དྲན་པའི་ཆོས་ཚན་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '2668':
      image_group_id: I3CN5335
      title: ''
      total_pages: 324
      order: 1
      base_file: 2668.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
